# -*- coding: utf-8 -*-
"""Assignment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTbQrV36mBeJdTBONeSDSPwcN2wkU4_C
"""

#1. Simple Calculator
a=float(input("value of a"))
b=float(input("value of b"))
print("Addition of the two numbers=",a+b)
print("Substraction of the two numbers=",a-b)
print("Multiplication of two numbers=",a*b)
print("Division of two numbers=",a/b)
print("Modulus of two numbers=",a%b)
print("Exponential of two number=s",a**b)
print("Floor Division of two numbers=",a//b)

#2.Simple Intrest
P=float(input("Enter the principle Amount"))
T=float(input("Enter the Time"))
R=float(input("Enter rate of intrest"))
SI=(P*T*R)/100
print("Simple Intrest=",SI)

#3.Area of circle
r=float(input("Enter the Radius of the circle="))
a=(22/7)*r**2
print("Area of the circle is",a)

#4.Area of Triangle
a=float(input("Enter the first side of the triangle"))
b=float(input("Enter the second side of the triangle"))
c=float(input("Enter the third side of the triangle"))
s=(a+b+c)/2
area=(s*(s-a)*(s-b)*(s-c))**0.5
print("The area of the triangle is",area)

#5.Celsius to Fahrenheit
c=float(input("enter the Temperature in celcius"))
f=(c*9/5)+32
print("temperature in fahrenheit is",f)

#6.Area of Rectangle
l=float(input("enter the length of the Rectangle"))
b=float(input("enter the Breadth of the Rectangle"))
a=l*b
print("the area of the Rectangle is",a)

#7.Perimeter of Square
s=float(input("enter the side of the Square"))
a=4*s
print("perimeter of the square is",a)

#8.Circumference of a Circle
r=float(input("enter the radius of circle"))
c=2*(22/7)*r
print("circumference of the circle is",c)

#9.Swaping of two Numbers
a=float(input("value of a"))
b=float(input("value of b"))
temp,a=a,b
b=temp
print("the value of a after swapping=",a)
print("the value of b after swapping=",b)

